### PR TITLE
Deletes old repports for spring 7 and 8

### PR DESCRIPTION
**Pull request by Edsen93**
I think for testing purpose it's important to delete the previously reported when a new test is ran.

If a report is create after that, you chose to change the test name and run the test again.
Now you have two reports in your directory

### CODE REVIEW

**Comment by rohwerj** [comment]
I'm not convinced that it's a good idea to delete old reports when a new test is run.
This is a change of the behavior and I'm not sure, if there are not some use cases where you want the old reports to still be there.
I unterstand your intention and maybe it would be possible to integrate this as an opt-in feature.

**Comment by ingorichtsmeier** [comment]
You can easily clean old tests with maven without any additional code required: `mvn clean test`.

**Comment by rohwerj** [comment]
I agree with Ingo. Normally the tests are run with Maven or Gradle and with those tools you can easily clean the build directory. 
Anyway I think your solution would not work as you are using the suite name to find the directory to delete. As the suite name is built from the test class you would never be able to delete the directory from a renamed test this way.

**Comment by Edsen93** [comment]
@ingorichtsmeier  You're right. Will close pull request.

**Pull request closed without merging**
